### PR TITLE
Update sequence search

### PR DESCRIPTION
**Pull request by emilhaegglund**
Hi,
These changes would need an update to the tests for sequence search as the format on the output table is slightly different, it includes the query id, and separating the accession and name into two columns.
Let me know what you think.

Best regards,
Emil Hägglund

### CODE REVIEW

**Comment by mberacochea** [comment]
Dear Emil,

Thank you for the PR, most welcomed. I'll review this in the next few days and will get back to you.

Cheers

**Comment by mberacochea** [comment]
I'm closing in favor of https://github.com/EBI-Metagenomics/emg-toolkit/pull/18

**Review by caballero — COMMENTED** [review]
changes as ok

**Review by caballero — COMMENTED** [review]
readme update is ok

**Pull request closed without merging**
